name: CI/CD Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: [build]

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [test]

  deploy-test:
    uses: ./.github/workflows/deploy.yml
    with:
      releaseType: 'test'
    secrets: inherit
    needs: [publish]

  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      releaseType: 'production'
    secrets: inherit
    needs: [deploy-test]