# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches: 
    include:
      - main
  paths:
    exclude:
      - AzureWorkshopInfrastruktur

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
    - job: build
      steps:  
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish $(buildConfiguration)'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'AzureWorkshop/AzureWorkshop.sln'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: 'test'
          projects: 'AzureWorkshop/AzureWorkshopAppTests/AzureWorkshopAppTests.csproj'
          testRunTitle: 'dotnet core run test'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
  - stage: deploy_test
    jobs:
      - deployment: deploy
        environment: Test
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download artifacts'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.DefaultWorkingDirectory)'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy web app to azure'
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Test'
                  appType: 'webApp'
                  WebAppName: 'workshop2-knutel-test'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  - stage: deploy_prod
    jobs:
      - deployment: deploy
        environment: Prod
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download artifacts'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'drop'
                  downloadPath: '$(System.DefaultWorkingDirectory)'
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy web app to azure'
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Test'
                  appType: 'webApp'
                  WebAppName: 'workshop2-knutel-prod'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'